name: Hexo Generated
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Package
        run: |
          npm install -g

      - name: Build
        run: npm run build

      - name: Add
        run: |
          mv public/ docs/
          git add docs/
          git config --global user.email "56037046+FionJones@users.noreply.github.com"
          git config --global user.name "FionJones"
          git commit -m "Build Public"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}